// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comp.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearAssignedRoles = `-- name: ClearAssignedRoles :exec
UPDATE signups SET assigned_role = NULL
WHERE event_id = $1
`

// Locking any comp_name overwrites the whole event's assigned_role, since that
// column is single-valued while comp_slots holds multiple named drafts.
func (q *Queries) ClearAssignedRoles(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearAssignedRoles, eventID)
	return err
}

const deleteComp = `-- name: DeleteComp :exec
DELETE FROM comps
WHERE event_id = $1 AND name = $2
`

type DeleteCompParams struct {
	EventID uuid.UUID
	Name    string
}

func (q *Queries) DeleteComp(ctx context.Context, arg DeleteCompParams) error {
	_, err := q.db.Exec(ctx, deleteComp, arg.EventID, arg.Name)
	return err
}

const deleteCompSlots = `-- name: DeleteCompSlots :exec
DELETE FROM comp_slots
WHERE event_id = $1 AND comp_name = $2
`

type DeleteCompSlotsParams struct {
	EventID  uuid.UUID
	CompName string
}

func (q *Queries) DeleteCompSlots(ctx context.Context, arg DeleteCompSlotsParams) error {
	_, err := q.db.Exec(ctx, deleteCompSlots, arg.EventID, arg.CompName)
	return err
}

const dropCompSlotsForCharacter = `-- name: DropCompSlotsForCharacter :many
DELETE FROM comp_slots cs
WHERE cs.event_id = $1 AND cs.character_id = $2
  AND NOT EXISTS (
      SELECT 1 FROM signups s
      WHERE s.event_id = cs.event_id
        AND s.character_id = cs.character_id
        AND s.status IN ('CONFIRMED', 'LATE')
  )
RETURNING cs.comp_name
`

type DropCompSlotsForCharacterParams struct {
	EventID     uuid.UUID
	CharacterID uuid.UUID
}

// A signup that leaves the assignment pool takes its seats with it. Without this the
// locked comp keeps a slot for someone who has said they are not coming, and
// CountCompSlotsForEvent still reads the event as locked.
//
// The pool test is written here rather than in Go so it stays next to the one in
// ListAssignmentPoolForEvent above: two definitions of "holds a seat" that drift are
// how a raider ends up assigned and absent at once. Run it in the same transaction as
// the write it follows: after an upsert it reads back the status just written, and
// after a delete it finds no signup at all, which is the strongest form of not in the
// pool and is what a withdrawal means.
//
// One row per comp the character was in, never more: comp_slots is unique on
// (event_id, comp_name, character_id), so nobody holds two seats in one comp.
func (q *Queries) DropCompSlotsForCharacter(ctx context.Context, arg DropCompSlotsForCharacterParams) ([]string, error) {
	rows, err := q.db.Query(ctx, dropCompSlotsForCharacter, arg.EventID, arg.CharacterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var comp_name string
		if err := rows.Scan(&comp_name); err != nil {
			return nil, err
		}
		items = append(items, comp_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComp = `-- name: GetComp :one
SELECT id, event_id, name, mode FROM comps
WHERE event_id = $1 AND name = $2
`

type GetCompParams struct {
	EventID uuid.UUID
	Name    string
}

func (q *Queries) GetComp(ctx context.Context, arg GetCompParams) (Comp, error) {
	row := q.db.QueryRow(ctx, getComp, arg.EventID, arg.Name)
	var i Comp
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Mode,
	)
	return i, err
}

const insertCompSlot = `-- name: InsertCompSlot :exec
INSERT INTO comp_slots (id, event_id, comp_name, character_id, role, slot_index, is_bench, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertCompSlotParams struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	CompName    string
	CharacterID uuid.UUID
	Role        RoleEnum
	SlotIndex   int16
	IsBench     bool
	Reason      string
}

func (q *Queries) InsertCompSlot(ctx context.Context, arg InsertCompSlotParams) error {
	_, err := q.db.Exec(ctx, insertCompSlot,
		arg.ID,
		arg.EventID,
		arg.CompName,
		arg.CharacterID,
		arg.Role,
		arg.SlotIndex,
		arg.IsBench,
		arg.Reason,
	)
	return err
}

const listAssignmentPoolForEvent = `-- name: ListAssignmentPoolForEvent :many
SELECT
    s.character_id,
    c.name,
    c.is_main,
    c.ilvl,
    c.mplus_score,
    s.created_at AS signed_up_at
FROM signups s
JOIN characters c ON c.id = s.character_id
WHERE s.event_id = $1 AND s.status IN ('CONFIRMED', 'LATE')
ORDER BY s.created_at ASC, s.id ASC
`

type ListAssignmentPoolForEventRow struct {
	CharacterID uuid.UUID
	Name        string
	IsMain      bool
	Ilvl        pgtype.Numeric
	MplusScore  pgtype.Numeric
	SignedUpAt  pgtype.Timestamptz
}

// Confirmed and late signups only; declined, tentative, absent, and no-show never
// reach the assigner.
func (q *Queries) ListAssignmentPoolForEvent(ctx context.Context, eventID uuid.UUID) ([]ListAssignmentPoolForEventRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentPoolForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentPoolForEventRow
	for rows.Next() {
		var i ListAssignmentPoolForEventRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.Name,
			&i.IsMain,
			&i.Ilvl,
			&i.MplusScore,
			&i.SignedUpAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompSlots = `-- name: ListCompSlots :many
SELECT id, event_id, comp_name, character_id, role, slot_index, is_bench, reason FROM comp_slots
WHERE event_id = $1 AND comp_name = $2
ORDER BY is_bench, slot_index
`

type ListCompSlotsParams struct {
	EventID  uuid.UUID
	CompName string
}

func (q *Queries) ListCompSlots(ctx context.Context, arg ListCompSlotsParams) ([]CompSlot, error) {
	rows, err := q.db.Query(ctx, listCompSlots, arg.EventID, arg.CompName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompSlot
	for rows.Next() {
		var i CompSlot
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.CompName,
			&i.CharacterID,
			&i.Role,
			&i.SlotIndex,
			&i.IsBench,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComps = `-- name: ListComps :many
SELECT id, event_id, name, mode FROM comps
WHERE event_id = $1
ORDER BY name
`

func (q *Queries) ListComps(ctx context.Context, eventID uuid.UUID) ([]Comp, error) {
	rows, err := q.db.Query(ctx, listComps, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comp
	for rows.Next() {
		var i Comp
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesForCharacters = `-- name: ListRolesForCharacters :many
SELECT character_id, role, priority FROM character_roles
WHERE character_id = ANY($1::uuid[])
ORDER BY character_id, priority, role
`

func (q *Queries) ListRolesForCharacters(ctx context.Context, characterIds []uuid.UUID) ([]CharacterRole, error) {
	rows, err := q.db.Query(ctx, listRolesForCharacters, characterIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterRole
	for rows.Next() {
		var i CharacterRole
		if err := rows.Scan(&i.CharacterID, &i.Role, &i.Priority); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnseatedForComp = `-- name: ListUnseatedForComp :many
SELECT
    s.character_id,
    s.status,
    s.created_at AS signed_up_at,
    EXISTS (SELECT 1 FROM character_roles cr WHERE cr.character_id = s.character_id) AS has_roles
FROM signups s
WHERE s.event_id = $1
  AND s.status IN ('CONFIRMED', 'LATE')
  AND NOT EXISTS (
      SELECT 1 FROM comp_slots cs
      WHERE cs.event_id = s.event_id
        AND cs.comp_name = $2
        AND cs.character_id = s.character_id
  )
ORDER BY s.created_at DESC, s.id DESC
`

type ListUnseatedForCompParams struct {
	EventID  uuid.UUID
	CompName string
}

type ListUnseatedForCompRow struct {
	CharacterID uuid.UUID
	Status      SignupStatus
	SignedUpAt  pgtype.Timestamptz
	HasRoles    bool
}

// Who is in the assignment pool and holds no slot on this comp. A board is a snapshot
// taken by the last lock, and signups carry on after it, so this is how a raider who
// arrived since then is visible at all.
//
// The pool test sits here rather than in Go for the reason DropCompSlotsForCharacter
// gives below: it has to stay next to ListAssignmentPoolForEvent above.
//
// has_roles is what separates the two ways to end up here. Assign drops a character
// with an empty role menu, because comp_slots.role is NOT NULL and there is no role to
// record, so they are unseated by every lock rather than by arriving late.
//
// Newest first: the recent arrivals are what this answers.
func (q *Queries) ListUnseatedForComp(ctx context.Context, arg ListUnseatedForCompParams) ([]ListUnseatedForCompRow, error) {
	rows, err := q.db.Query(ctx, listUnseatedForComp, arg.EventID, arg.CompName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnseatedForCompRow
	for rows.Next() {
		var i ListUnseatedForCompRow
		if err := rows.Scan(
			&i.CharacterID,
			&i.Status,
			&i.SignedUpAt,
			&i.HasRoles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameComp = `-- name: RenameComp :exec
UPDATE comps SET name = $1
WHERE event_id = $2 AND name = $3
`

type RenameCompParams struct {
	NewName string
	EventID uuid.UUID
	Name    string
}

// The slots follow, through the ON UPDATE CASCADE added in migration 00011. Renaming
// rather than rebuilding is the point: changing a label should not cost the board
// underneath it.
func (q *Queries) RenameComp(ctx context.Context, arg RenameCompParams) error {
	_, err := q.db.Exec(ctx, renameComp, arg.NewName, arg.EventID, arg.Name)
	return err
}

const setCompMode = `-- name: SetCompMode :exec
UPDATE comps SET mode = $3
WHERE event_id = $1 AND name = $2
`

type SetCompModeParams struct {
	EventID uuid.UUID
	Name    string
	Mode    CompMode
}

func (q *Queries) SetCompMode(ctx context.Context, arg SetCompModeParams) error {
	_, err := q.db.Exec(ctx, setCompMode, arg.EventID, arg.Name, arg.Mode)
	return err
}

const setSignupAssignedRole = `-- name: SetSignupAssignedRole :exec
UPDATE signups SET assigned_role = $3
WHERE event_id = $1 AND character_id = $2
`

type SetSignupAssignedRoleParams struct {
	EventID      uuid.UUID
	CharacterID  uuid.UUID
	AssignedRole *RoleEnum
}

func (q *Queries) SetSignupAssignedRole(ctx context.Context, arg SetSignupAssignedRoleParams) error {
	_, err := q.db.Exec(ctx, setSignupAssignedRole, arg.EventID, arg.CharacterID, arg.AssignedRole)
	return err
}

const upsertComp = `-- name: UpsertComp :one
INSERT INTO comps (id, event_id, name, mode)
VALUES ($1, $2, $3, $4)
ON CONFLICT (event_id, name) DO UPDATE SET name = excluded.name
RETURNING id, event_id, name, mode
`

type UpsertCompParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
	Name    string
	Mode    CompMode
}

// Creating a comp is idempotent, but the mode is set once at creation: flipping an
// existing comp between AUTO and MANUAL is SetCompMode's job, so a stray create
// cannot quietly hand a raid lead's hand-built comp back to the assigner.
func (q *Queries) UpsertComp(ctx context.Context, arg UpsertCompParams) (Comp, error) {
	row := q.db.QueryRow(ctx, upsertComp,
		arg.ID,
		arg.EventID,
		arg.Name,
		arg.Mode,
	)
	var i Comp
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Mode,
	)
	return i, err
}
