// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guildsettings.sql

package db

import (
	"context"
)

const getGuildSettings = `-- name: GetGuildSettings :one
SELECT discord_guild_id, events_channel_id, updated_at, timezone, event_mention_role_ids, event_banner_url, reminder_lead_minutes, reminder_delivery, warcraft_logs_client_id, warcraft_logs_key_sealed, warcraft_logs_key_set_at FROM guild_settings
WHERE discord_guild_id = $1
`

func (q *Queries) GetGuildSettings(ctx context.Context, discordGuildID int64) (GuildSetting, error) {
	row := q.db.QueryRow(ctx, getGuildSettings, discordGuildID)
	var i GuildSetting
	err := row.Scan(
		&i.DiscordGuildID,
		&i.EventsChannelID,
		&i.UpdatedAt,
		&i.Timezone,
		&i.EventMentionRoleIds,
		&i.EventBannerUrl,
		&i.ReminderLeadMinutes,
		&i.ReminderDelivery,
		&i.WarcraftLogsClientID,
		&i.WarcraftLogsKeySealed,
		&i.WarcraftLogsKeySetAt,
	)
	return i, err
}

const upsertGuildSettings = `-- name: UpsertGuildSettings :one
INSERT INTO guild_settings (discord_guild_id, events_channel_id, timezone, event_mention_role_ids, event_banner_url, reminder_lead_minutes, reminder_delivery)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (discord_guild_id) DO UPDATE
SET events_channel_id = excluded.events_channel_id,
    timezone = excluded.timezone,
    event_mention_role_ids = excluded.event_mention_role_ids,
    event_banner_url = excluded.event_banner_url,
    reminder_lead_minutes = excluded.reminder_lead_minutes,
    reminder_delivery = excluded.reminder_delivery,
    updated_at = now()
RETURNING discord_guild_id, events_channel_id, updated_at, timezone, event_mention_role_ids, event_banner_url, reminder_lead_minutes, reminder_delivery, warcraft_logs_client_id, warcraft_logs_key_sealed, warcraft_logs_key_set_at
`

type UpsertGuildSettingsParams struct {
	DiscordGuildID      int64
	EventsChannelID     *int64
	Timezone            *string
	EventMentionRoleIds []int64
	EventBannerUrl      *string
	ReminderLeadMinutes *int32
	ReminderDelivery    *ReminderDelivery
}

// Whole-row write. There is one settable field today and a guild that has never been
// configured has no row, so an upsert is both the create and the update.
func (q *Queries) UpsertGuildSettings(ctx context.Context, arg UpsertGuildSettingsParams) (GuildSetting, error) {
	row := q.db.QueryRow(ctx, upsertGuildSettings,
		arg.DiscordGuildID,
		arg.EventsChannelID,
		arg.Timezone,
		arg.EventMentionRoleIds,
		arg.EventBannerUrl,
		arg.ReminderLeadMinutes,
		arg.ReminderDelivery,
	)
	var i GuildSetting
	err := row.Scan(
		&i.DiscordGuildID,
		&i.EventsChannelID,
		&i.UpdatedAt,
		&i.Timezone,
		&i.EventMentionRoleIds,
		&i.EventBannerUrl,
		&i.ReminderLeadMinutes,
		&i.ReminderDelivery,
		&i.WarcraftLogsClientID,
		&i.WarcraftLogsKeySealed,
		&i.WarcraftLogsKeySetAt,
	)
	return i, err
}
