// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelJobsForEvent = `-- name: CancelJobsForEvent :exec
UPDATE scheduled_jobs SET status = 'CANCELED'
WHERE event_id = $1 AND status = 'PENDING'
`

func (q *Queries) CancelJobsForEvent(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelJobsForEvent, eventID)
	return err
}

const claimDueJobs = `-- name: ClaimDueJobs :many
SELECT id, event_id, job_type, run_at, status, attempts, skip_reason FROM scheduled_jobs
WHERE status = 'PENDING' AND run_at <= now()
ORDER BY run_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ClaimDueJobs(ctx context.Context, rowLimit int32) ([]ScheduledJob, error) {
	rows, err := q.db.Query(ctx, claimDueJobs, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledJob
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.JobType,
			&i.RunAt,
			&i.Status,
			&i.Attempts,
			&i.SkipReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreEventReminderJob = `-- name: GetPreEventReminderJob :one
SELECT id, event_id, job_type, run_at, status, attempts, skip_reason FROM scheduled_jobs
WHERE event_id = $1 AND job_type = 'REMINDER_PRE_EVENT'
ORDER BY (status = 'CANCELED'), run_at DESC
LIMIT 1
`

// The pre-event reminder an event currently has, for reporting what became of it.
// An edit cancels the old jobs and schedules new ones, so a long-lived event has more
// than one row here: the live one is what to report, and CANCELED sorts last.
func (q *Queries) GetPreEventReminderJob(ctx context.Context, eventID uuid.UUID) (ScheduledJob, error) {
	row := q.db.QueryRow(ctx, getPreEventReminderJob, eventID)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.JobType,
		&i.RunAt,
		&i.Status,
		&i.Attempts,
		&i.SkipReason,
	)
	return i, err
}

const markJobFailed = `-- name: MarkJobFailed :exec
UPDATE scheduled_jobs SET status = $2, attempts = attempts + 1
WHERE id = $1
`

type MarkJobFailedParams struct {
	ID     uuid.UUID
	Status JobStatus
}

// Caller decides PENDING (retry) or FAILED (give up) based on the attempts it read
// off the claimed row; this just records the attempt.
func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) error {
	_, err := q.db.Exec(ctx, markJobFailed, arg.ID, arg.Status)
	return err
}

const markJobSent = `-- name: MarkJobSent :exec
UPDATE scheduled_jobs SET status = 'SENT'
WHERE id = $1
`

func (q *Queries) MarkJobSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markJobSent, id)
	return err
}

const markJobSkipped = `-- name: MarkJobSkipped :exec
UPDATE scheduled_jobs SET status = 'SENT', skip_reason = $2
WHERE id = $1
`

type MarkJobSkippedParams struct {
	ID         uuid.UUID
	SkipReason *string
}

// Done, but it notified nobody, and the reason says why. Status stays SENT because the
// job is finished either way; what changes is that the row no longer claims a send it
// did not make.
func (q *Queries) MarkJobSkipped(ctx context.Context, arg MarkJobSkippedParams) error {
	_, err := q.db.Exec(ctx, markJobSkipped, arg.ID, arg.SkipReason)
	return err
}

const scheduleJob = `-- name: ScheduleJob :exec
INSERT INTO scheduled_jobs (id, event_id, job_type, run_at)
VALUES ($1, $2, $3, $4)
`

type ScheduleJobParams struct {
	ID      uuid.UUID
	EventID uuid.UUID
	JobType JobEnum
	RunAt   pgtype.Timestamptz
}

func (q *Queries) ScheduleJob(ctx context.Context, arg ScheduleJobParams) error {
	_, err := q.db.Exec(ctx, scheduleJob,
		arg.ID,
		arg.EventID,
		arg.JobType,
		arg.RunAt,
	)
	return err
}
