// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BillingPeriodEnum string

const (
	BillingPeriodEnumMONTHLY BillingPeriodEnum = "MONTHLY"
	BillingPeriodEnumYEARLY  BillingPeriodEnum = "YEARLY"
)

func (e *BillingPeriodEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingPeriodEnum(s)
	case string:
		*e = BillingPeriodEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingPeriodEnum: %T", src)
	}
	return nil
}

type NullBillingPeriodEnum struct {
	BillingPeriodEnum BillingPeriodEnum
	Valid             bool // Valid is true if BillingPeriodEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingPeriodEnum) Scan(value interface{}) error {
	if value == nil {
		ns.BillingPeriodEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingPeriodEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingPeriodEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingPeriodEnum), nil
}

type CompMode string

const (
	CompModeAUTO   CompMode = "AUTO"
	CompModeMANUAL CompMode = "MANUAL"
)

func (e *CompMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompMode(s)
	case string:
		*e = CompMode(s)
	default:
		return fmt.Errorf("unsupported scan type for CompMode: %T", src)
	}
	return nil
}

type NullCompMode struct {
	CompMode CompMode
	Valid    bool // Valid is true if CompMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompMode) Scan(value interface{}) error {
	if value == nil {
		ns.CompMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompMode), nil
}

type DiscordChannelType string

const (
	DiscordChannelTypeTEXT         DiscordChannelType = "TEXT"
	DiscordChannelTypeANNOUNCEMENT DiscordChannelType = "ANNOUNCEMENT"
	DiscordChannelTypeVOICE        DiscordChannelType = "VOICE"
	DiscordChannelTypeSTAGEVOICE   DiscordChannelType = "STAGE_VOICE"
	DiscordChannelTypeFORUM        DiscordChannelType = "FORUM"
	DiscordChannelTypeCATEGORY     DiscordChannelType = "CATEGORY"
	DiscordChannelTypeOTHER        DiscordChannelType = "OTHER"
)

func (e *DiscordChannelType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscordChannelType(s)
	case string:
		*e = DiscordChannelType(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscordChannelType: %T", src)
	}
	return nil
}

type NullDiscordChannelType struct {
	DiscordChannelType DiscordChannelType
	Valid              bool // Valid is true if DiscordChannelType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscordChannelType) Scan(value interface{}) error {
	if value == nil {
		ns.DiscordChannelType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscordChannelType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscordChannelType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscordChannelType), nil
}

type EventType string

const (
	EventTypeRAID       EventType = "RAID"
	EventTypeMYTHICPLUS EventType = "MYTHIC_PLUS"
)

func (e *EventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventType(s)
	case string:
		*e = EventType(s)
	default:
		return fmt.Errorf("unsupported scan type for EventType: %T", src)
	}
	return nil
}

type NullEventType struct {
	EventType EventType
	Valid     bool // Valid is true if EventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventType) Scan(value interface{}) error {
	if value == nil {
		ns.EventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventType), nil
}

type JobEnum string

const (
	JobEnumSIGNUPDEADLINE   JobEnum = "SIGNUP_DEADLINE"
	JobEnumREMINDER24H      JobEnum = "REMINDER_24H"
	JobEnumREMINDERPREEVENT JobEnum = "REMINDER_PRE_EVENT"
	JobEnumCOMPNAG          JobEnum = "COMP_NAG"
)

func (e *JobEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobEnum(s)
	case string:
		*e = JobEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for JobEnum: %T", src)
	}
	return nil
}

type NullJobEnum struct {
	JobEnum JobEnum
	Valid   bool // Valid is true if JobEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobEnum) Scan(value interface{}) error {
	if value == nil {
		ns.JobEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobEnum), nil
}

type JobStatus string

const (
	JobStatusPENDING  JobStatus = "PENDING"
	JobStatusSENT     JobStatus = "SENT"
	JobStatusFAILED   JobStatus = "FAILED"
	JobStatusCANCELED JobStatus = "CANCELED"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus
	Valid     bool // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type NotificationKind string

const (
	NotificationKindREMINDER24H      NotificationKind = "REMINDER_24H"
	NotificationKindREMINDERPREEVENT NotificationKind = "REMINDER_PRE_EVENT"
	NotificationKindSIGNUPDEADLINE   NotificationKind = "SIGNUP_DEADLINE"
	NotificationKindCOMPNAG          NotificationKind = "COMP_NAG"
	NotificationKindLATEREQUESTFILED NotificationKind = "LATE_REQUEST_FILED"
	NotificationKindROSTERUPDATED    NotificationKind = "ROSTER_UPDATED"
	NotificationKindCOMPSLOTDROPPED  NotificationKind = "COMP_SLOT_DROPPED"
	NotificationKindEVENTCREATED     NotificationKind = "EVENT_CREATED"
	NotificationKindSIGNUPCHANGED    NotificationKind = "SIGNUP_CHANGED"
	NotificationKindCOMPCHANGED      NotificationKind = "COMP_CHANGED"
	NotificationKindEVENTCHANGED     NotificationKind = "EVENT_CHANGED"
	NotificationKindDELIVERYFAILED   NotificationKind = "DELIVERY_FAILED"
)

func (e *NotificationKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationKind(s)
	case string:
		*e = NotificationKind(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationKind: %T", src)
	}
	return nil
}

type NullNotificationKind struct {
	NotificationKind NotificationKind
	Valid            bool // Valid is true if NotificationKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationKind) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationKind), nil
}

type NotificationTarget string

const (
	NotificationTargetUSER    NotificationTarget = "USER"
	NotificationTargetROLE    NotificationTarget = "ROLE"
	NotificationTargetMESSAGE NotificationTarget = "MESSAGE"
	NotificationTargetCHANNEL NotificationTarget = "CHANNEL"
)

func (e *NotificationTarget) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationTarget(s)
	case string:
		*e = NotificationTarget(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationTarget: %T", src)
	}
	return nil
}

type NullNotificationTarget struct {
	NotificationTarget NotificationTarget
	Valid              bool // Valid is true if NotificationTarget is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationTarget) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationTarget, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationTarget.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationTarget) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationTarget), nil
}

type RaidDifficulty string

const (
	RaidDifficultyNORMAL RaidDifficulty = "NORMAL"
	RaidDifficultyHEROIC RaidDifficulty = "HEROIC"
	RaidDifficultyMYTHIC RaidDifficulty = "MYTHIC"
)

func (e *RaidDifficulty) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RaidDifficulty(s)
	case string:
		*e = RaidDifficulty(s)
	default:
		return fmt.Errorf("unsupported scan type for RaidDifficulty: %T", src)
	}
	return nil
}

type NullRaidDifficulty struct {
	RaidDifficulty RaidDifficulty
	Valid          bool // Valid is true if RaidDifficulty is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRaidDifficulty) Scan(value interface{}) error {
	if value == nil {
		ns.RaidDifficulty, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RaidDifficulty.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRaidDifficulty) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RaidDifficulty), nil
}

type ReminderDelivery string

const (
	ReminderDeliveryPING ReminderDelivery = "PING"
	ReminderDeliveryDM   ReminderDelivery = "DM"
	ReminderDeliveryBOTH ReminderDelivery = "BOTH"
)

func (e *ReminderDelivery) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReminderDelivery(s)
	case string:
		*e = ReminderDelivery(s)
	default:
		return fmt.Errorf("unsupported scan type for ReminderDelivery: %T", src)
	}
	return nil
}

type NullReminderDelivery struct {
	ReminderDelivery ReminderDelivery
	Valid            bool // Valid is true if ReminderDelivery is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReminderDelivery) Scan(value interface{}) error {
	if value == nil {
		ns.ReminderDelivery, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReminderDelivery.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReminderDelivery) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReminderDelivery), nil
}

type RequestState string

const (
	RequestStatePENDING  RequestState = "PENDING"
	RequestStateAPPROVED RequestState = "APPROVED"
	RequestStateREJECTED RequestState = "REJECTED"
)

func (e *RequestState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestState(s)
	case string:
		*e = RequestState(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestState: %T", src)
	}
	return nil
}

type NullRequestState struct {
	RequestState RequestState
	Valid        bool // Valid is true if RequestState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestState) Scan(value interface{}) error {
	if value == nil {
		ns.RequestState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestState), nil
}

type RoleEnum string

const (
	RoleEnumTANK   RoleEnum = "TANK"
	RoleEnumHEALER RoleEnum = "HEALER"
	RoleEnumMDPS   RoleEnum = "MDPS"
	RoleEnumRDPS   RoleEnum = "RDPS"
)

func (e *RoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleEnum(s)
	case string:
		*e = RoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleEnum: %T", src)
	}
	return nil
}

type NullRoleEnum struct {
	RoleEnum RoleEnum
	Valid    bool // Valid is true if RoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.RoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleEnum), nil
}

type SignupStatus string

const (
	SignupStatusCONFIRMED SignupStatus = "CONFIRMED"
	SignupStatusTENTATIVE SignupStatus = "TENTATIVE"
	SignupStatusDECLINED  SignupStatus = "DECLINED"
	SignupStatusLATE      SignupStatus = "LATE"
	SignupStatusABSENT    SignupStatus = "ABSENT"
	SignupStatusNOSHOW    SignupStatus = "NO_SHOW"
)

func (e *SignupStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SignupStatus(s)
	case string:
		*e = SignupStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SignupStatus: %T", src)
	}
	return nil
}

type NullSignupStatus struct {
	SignupStatus SignupStatus
	Valid        bool // Valid is true if SignupStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSignupStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SignupStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SignupStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSignupStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SignupStatus), nil
}

type SubStatusEnum string

const (
	SubStatusEnumACTIVE   SubStatusEnum = "ACTIVE"
	SubStatusEnumPASTDUE  SubStatusEnum = "PAST_DUE"
	SubStatusEnumCANCELED SubStatusEnum = "CANCELED"
	SubStatusEnumTRIALING SubStatusEnum = "TRIALING"
)

func (e *SubStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubStatusEnum(s)
	case string:
		*e = SubStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for SubStatusEnum: %T", src)
	}
	return nil
}

type NullSubStatusEnum struct {
	SubStatusEnum SubStatusEnum
	Valid         bool // Valid is true if SubStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.SubStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubStatusEnum), nil
}

type TierEnum string

const (
	TierEnumFREE    TierEnum = "FREE"
	TierEnumPREMIUM TierEnum = "PREMIUM"
)

func (e *TierEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TierEnum(s)
	case string:
		*e = TierEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TierEnum: %T", src)
	}
	return nil
}

type NullTierEnum struct {
	TierEnum TierEnum
	Valid    bool // Valid is true if TierEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTierEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TierEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TierEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTierEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TierEnum), nil
}

type Character struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Name             string
	Realm            string
	Class            *string
	Spec             *string
	Ilvl             pgtype.Numeric
	MplusScore       pgtype.Numeric
	LastSynced       pgtype.Timestamptz
	IsMain           bool
	Region           string
	SyncAttemptedAt  pgtype.Timestamptz
	EnchantsMissing  *int16
	EnchantsExpected *int16
	TierPieces       *int16
	RaidSlug         *string
	RaidBosses       *int16
	RaidNormalKilled *int16
	RaidHeroicKilled *int16
	RaidMythicKilled *int16
	ArchivedAt       pgtype.Timestamptz
	NotFoundSince    pgtype.Timestamptz
}

type CharacterRole struct {
	CharacterID uuid.UUID
	Role        RoleEnum
	Priority    int16
}

type CharacterSnapshot struct {
	ID          uuid.UUID
	CharacterID uuid.UUID
	CapturedAt  pgtype.Timestamptz
	Ilvl        pgtype.Numeric
	MplusScore  pgtype.Numeric
	Gear        []byte
}

type Comp struct {
	ID      uuid.UUID
	EventID uuid.UUID
	Name    string
	Mode    CompMode
}

type CompSlot struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	CompName    string
	CharacterID uuid.UUID
	Role        RoleEnum
	SlotIndex   int16
	IsBench     bool
	Reason      string
}

type Event struct {
	ID                  uuid.UUID
	DiscordGuildID      int64
	Type                EventType
	Title               string
	StartsAt            pgtype.Timestamptz
	SignupDeadline      pgtype.Timestamptz
	CompTemplate        []byte
	MessageID           *int64
	ChannelID           *int64
	Difficulty          *RaidDifficulty
	ReminderLeadMinutes *int32
	WarcraftlogsUrl     *string
}

type GuildChannel struct {
	DiscordGuildID   int64
	DiscordChannelID int64
	Name             string
	Type             DiscordChannelType
}

type GuildRaidLeadRole struct {
	DiscordGuildID int64
	DiscordRoleID  int64
}

type GuildRole struct {
	DiscordGuildID int64
	DiscordRoleID  int64
	Name           string
	Color          int32
	Position       int32
}

type GuildSetting struct {
	DiscordGuildID      int64
	EventsChannelID     *int64
	UpdatedAt           pgtype.Timestamptz
	Timezone            *string
	EventMentionRoleIds []int64
	EventBannerUrl      *string
	ReminderLeadMinutes *int32
	ReminderDelivery    *ReminderDelivery
}

type LateSignupRequest struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	CharacterID uuid.UUID
	Status      SignupStatus
	Note        *string
	State       RequestState
	CreatedAt   pgtype.Timestamptz
	DecidedAt   pgtype.Timestamptz
	LateUntil   pgtype.Timestamptz
}

type Notification struct {
	ID             uuid.UUID
	DiscordGuildID int64
	EventID        uuid.UUID
	Kind           NotificationKind
	TargetKind     NotificationTarget
	DiscordID      *int64
	RoleIds        []int64
	ChannelID      *int64
	Payload        []byte
	CreatedAt      pgtype.Timestamptz
	DeliveredAt    pgtype.Timestamptz
	ClaimedAt      pgtype.Timestamptz
	DiscordIds     []int64
}

type ScheduledJob struct {
	ID         uuid.UUID
	EventID    uuid.UUID
	JobType    JobEnum
	RunAt      pgtype.Timestamptz
	Status     JobStatus
	Attempts   int16
	SkipReason *string
}

type Signup struct {
	ID           uuid.UUID
	EventID      uuid.UUID
	CharacterID  uuid.UUID
	Status       SignupStatus
	AssignedRole *RoleEnum
	LateUntil    pgtype.Timestamptz
	Note         *string
	CreatedAt    pgtype.Timestamptz
}

type Subscription struct {
	ID               uuid.UUID
	DiscordGuildID   int64
	Tier             TierEnum
	BillingPeriod    *BillingPeriodEnum
	ProviderSubID    *string
	Status           SubStatusEnum
	PriceLockedAt    pgtype.Numeric
	CurrentPeriodEnd pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	ID             uuid.UUID
	DiscordID      int64
	DiscordGuildID int64
	CreatedAt      pgtype.Timestamptz
}
