// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNotifications = `-- name: ClaimNotifications :many
UPDATE notifications SET claimed_at = now()
WHERE id IN (
    SELECT n.id FROM notifications n
    WHERE n.delivered_at IS NULL
      AND (n.claimed_at IS NULL OR n.claimed_at < $1)
      AND ($2::bigint IS NULL OR n.discord_guild_id = $2)
    ORDER BY n.created_at ASC
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, discord_guild_id, event_id, kind, target_kind, discord_id, role_ids, channel_id, payload, created_at, delivered_at, claimed_at, discord_ids
`

type ClaimNotificationsParams struct {
	ClaimedBefore pgtype.Timestamptz
	GuildID       *int64
	RowLimit      int32
}

// Claiming, not just reading. The ack arrives in a later HTTP request, so no
// transaction can span send and ack and row locks cannot help: two bot replicas
// polling the same window would both read the same rows and DM every raider twice.
// Stamping claimed_at inside the same statement hands each row to one poller.
//
// claimed_before re-opens a lease so a bot that claimed rows and died still gets them
// redelivered. That keeps delivery at-least-once, which reminders tolerate; what it
// removes is the duplicate storm on every tick.
func (q *Queries) ClaimNotifications(ctx context.Context, arg ClaimNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, claimNotifications, arg.ClaimedBefore, arg.GuildID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.DiscordGuildID,
			&i.EventID,
			&i.Kind,
			&i.TargetKind,
			&i.DiscordID,
			&i.RoleIds,
			&i.ChannelID,
			&i.Payload,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.ClaimedAt,
			&i.DiscordIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotification = `-- name: GetNotification :one
SELECT id, discord_guild_id, event_id, kind, target_kind, discord_id, role_ids, channel_id, payload, created_at, delivered_at, claimed_at, discord_ids FROM notifications WHERE id = $1
`

// One outbox row by id. The failure report the bot files needs to know what it could
// not deliver and for which event.
func (q *Queries) GetNotification(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.DiscordGuildID,
		&i.EventID,
		&i.Kind,
		&i.TargetKind,
		&i.DiscordID,
		&i.RoleIds,
		&i.ChannelID,
		&i.Payload,
		&i.CreatedAt,
		&i.DeliveredAt,
		&i.ClaimedAt,
		&i.DiscordIds,
	)
	return i, err
}

const insertNotification = `-- name: InsertNotification :execrows
INSERT INTO notifications (id, discord_guild_id, event_id, kind, target_kind, discord_id, role_ids, discord_ids, channel_id, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT DO NOTHING
`

type InsertNotificationParams struct {
	ID             uuid.UUID
	DiscordGuildID int64
	EventID        uuid.UUID
	Kind           NotificationKind
	TargetKind     NotificationTarget
	DiscordID      *int64
	RoleIds        []int64
	DiscordIds     []int64
	ChannelID      *int64
	Payload        []byte
}

// The row count tells a suppressed insert from a real one, which is the only way a
// caller can see the coalescing below happen.
//
// ON CONFLICT DO NOTHING serves the roster redraws, which lean on
// notifications_roster_updated_pending: the second character to change on the same
// raid finds a redraw already queued and adds nothing. It is inert for every other
// kind, since the partial index does not cover them and the id comes from db.NewID.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNotification,
		arg.ID,
		arg.DiscordGuildID,
		arg.EventID,
		arg.Kind,
		arg.TargetKind,
		arg.DiscordID,
		arg.RoleIds,
		arg.DiscordIds,
		arg.ChannelID,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listEventsNeedingRosterRedraw = `-- name: ListEventsNeedingRosterRedraw :many
SELECT e.id, e.discord_guild_id, e.channel_id
FROM events e
JOIN signups s ON s.event_id = e.id
WHERE s.character_id = $1
  AND e.starts_at > now()
  AND e.message_id IS NOT NULL
  AND e.channel_id IS NOT NULL
`

type ListEventsNeedingRosterRedrawRow struct {
	ID             uuid.UUID
	DiscordGuildID int64
	ChannelID      *int64
}

// The posted, upcoming events this character is signed up to, one redraw apiece. The
// caller inserts the notifications on the same transaction as the snapshot that
// caused them, so no redraw is queued for a sync that was rolled back and none is
// lost for one that was not. Two statements rather than the INSERT ... SELECT this
// used to be, because the ids are generated in Go and the row count is not known
// until this query has run.
//
// Past events are skipped because nobody re-reads a raid that already happened, and
// events with no message_id were never posted, so there is nothing to edit.
func (q *Queries) ListEventsNeedingRosterRedraw(ctx context.Context, characterID uuid.UUID) ([]ListEventsNeedingRosterRedrawRow, error) {
	rows, err := q.db.Query(ctx, listEventsNeedingRosterRedraw, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsNeedingRosterRedrawRow
	for rows.Next() {
		var i ListEventsNeedingRosterRedrawRow
		if err := rows.Scan(&i.ID, &i.DiscordGuildID, &i.ChannelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationDelivered = `-- name: MarkNotificationDelivered :execrows
UPDATE notifications SET delivered_at = now()
WHERE id = $1
  AND ($2::bigint IS NULL OR discord_guild_id = $2)
`

type MarkNotificationDeliveredParams struct {
	ID      uuid.UUID
	GuildID *int64
}

// guild_id is optional, and the two callers differ. The bot acks across every guild
// from behind the service key, so it passes NULL. Anything reached by a raider's
// interaction must pass their guild, or acking by id alone would let them silently
// suppress another guild's reminders. Returning the row count lets the caller tell
// "not yours or not found" from "done".
func (q *Queries) MarkNotificationDelivered(ctx context.Context, arg MarkNotificationDeliveredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationDelivered, arg.ID, arg.GuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
