// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: raidlog.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueReports = `-- name: ClaimDueReports :many
UPDATE event_reports SET next_attempt_at = now() + interval '10 minutes'
WHERE event_id IN (
    SELECT event_id FROM event_reports
    WHERE next_attempt_at IS NOT NULL AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING event_id, host, code, status, revision, live, title, zone_name, region, report_starts_at, report_ends_at, fetched_at, next_attempt_at, attempts, failure_reason
`

// One statement, so two workers cannot take the same row.
//
// The ten minute push is a lease rather than a schedule: whatever the fetch decides
// overwrites it, and a worker that dies mid-fetch has its rows redelivered ten minutes
// later instead of never. Same at-least-once trade the notification outbox makes.
func (q *Queries) ClaimDueReports(ctx context.Context, rowLimit int32) ([]EventReport, error) {
	rows, err := q.db.Query(ctx, claimDueReports, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventReport
	for rows.Next() {
		var i EventReport
		if err := rows.Scan(
			&i.EventID,
			&i.Host,
			&i.Code,
			&i.Status,
			&i.Revision,
			&i.Live,
			&i.Title,
			&i.ZoneName,
			&i.Region,
			&i.ReportStartsAt,
			&i.ReportEndsAt,
			&i.FetchedAt,
			&i.NextAttemptAt,
			&i.Attempts,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearGuildWarcraftLogsCredentials = `-- name: ClearGuildWarcraftLogsCredentials :exec
UPDATE guild_settings SET
    warcraft_logs_client_id = NULL,
    warcraft_logs_key_sealed = NULL,
    warcraft_logs_key_set_at = NULL,
    updated_at = now()
WHERE discord_guild_id = $1
`

// Revoking. All three columns together, so a cleared key can never leave an id behind
// that looks configured.
func (q *Queries) ClearGuildWarcraftLogsCredentials(ctx context.Context, discordGuildID int64) error {
	_, err := q.db.Exec(ctx, clearGuildWarcraftLogsCredentials, discordGuildID)
	return err
}

const deleteEventReport = `-- name: DeleteEventReport :exec
DELETE FROM event_reports WHERE event_id = $1
`

// Taking the log off an event. The fights and raiders go with it by cascade.
func (q *Queries) DeleteEventReport(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventReport, eventID)
	return err
}

const deleteEventReportFightRaiders = `-- name: DeleteEventReportFightRaiders :exec
DELETE FROM event_report_fight_raiders WHERE event_id = $1
`

func (q *Queries) DeleteEventReportFightRaiders(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventReportFightRaiders, eventID)
	return err
}

const deleteEventReportFights = `-- name: DeleteEventReportFights :exec
DELETE FROM event_report_fights WHERE event_id = $1
`

func (q *Queries) DeleteEventReportFights(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventReportFights, eventID)
	return err
}

const deleteEventReportRaiders = `-- name: DeleteEventReportRaiders :exec
DELETE FROM event_report_raiders WHERE event_id = $1
`

func (q *Queries) DeleteEventReportRaiders(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventReportRaiders, eventID)
	return err
}

const getEventReport = `-- name: GetEventReport :one
SELECT event_id, host, code, status, revision, live, title, zone_name, region, report_starts_at, report_ends_at, fetched_at, next_attempt_at, attempts, failure_reason FROM event_reports WHERE event_id = $1
`

func (q *Queries) GetEventReport(ctx context.Context, eventID uuid.UUID) (EventReport, error) {
	row := q.db.QueryRow(ctx, getEventReport, eventID)
	var i EventReport
	err := row.Scan(
		&i.EventID,
		&i.Host,
		&i.Code,
		&i.Status,
		&i.Revision,
		&i.Live,
		&i.Title,
		&i.ZoneName,
		&i.Region,
		&i.ReportStartsAt,
		&i.ReportEndsAt,
		&i.FetchedAt,
		&i.NextAttemptAt,
		&i.Attempts,
		&i.FailureReason,
	)
	return i, err
}

const getEventReportStatuses = `-- name: GetEventReportStatuses :many
SELECT event_id, status FROM event_reports
WHERE event_id = ANY($1::uuid[])
`

type GetEventReportStatusesRow struct {
	EventID uuid.UUID
	Status  ReportStatus
}

// The status for a page of events at once, so the event list does not run a query per
// row to decide which link rel to offer.
func (q *Queries) GetEventReportStatuses(ctx context.Context, eventIds []uuid.UUID) ([]GetEventReportStatusesRow, error) {
	rows, err := q.db.Query(ctx, getEventReportStatuses, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventReportStatusesRow
	for rows.Next() {
		var i GetEventReportStatusesRow
		if err := rows.Scan(&i.EventID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuildWarcraftLogsCredentials = `-- name: GetGuildWarcraftLogsCredentials :one
SELECT warcraft_logs_client_id, warcraft_logs_key_sealed
FROM guild_settings
WHERE discord_guild_id = $1
`

type GetGuildWarcraftLogsCredentialsRow struct {
	WarcraftLogsClientID  *string
	WarcraftLogsKeySealed []byte
}

// The sealed key never leaves the service; this is the only query that reads it, and it
// is called by the worker, never by a request handler.
func (q *Queries) GetGuildWarcraftLogsCredentials(ctx context.Context, discordGuildID int64) (GetGuildWarcraftLogsCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getGuildWarcraftLogsCredentials, discordGuildID)
	var i GetGuildWarcraftLogsCredentialsRow
	err := row.Scan(&i.WarcraftLogsClientID, &i.WarcraftLogsKeySealed)
	return i, err
}

const insertEventReportFight = `-- name: InsertEventReportFight :exec
INSERT INTO event_report_fights (
    event_id, fight_id, encounter_id, name, difficulty, raid_size,
    kill, boss_percentage, fight_percentage, starts_at, ends_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11
)
ON CONFLICT (event_id, fight_id) DO UPDATE SET
    encounter_id = EXCLUDED.encounter_id,
    name = EXCLUDED.name,
    difficulty = EXCLUDED.difficulty,
    raid_size = EXCLUDED.raid_size,
    kill = EXCLUDED.kill,
    boss_percentage = EXCLUDED.boss_percentage,
    fight_percentage = EXCLUDED.fight_percentage,
    starts_at = EXCLUDED.starts_at,
    ends_at = EXCLUDED.ends_at
`

type InsertEventReportFightParams struct {
	EventID         uuid.UUID
	FightID         int32
	EncounterID     int32
	Name            string
	Difficulty      *int32
	RaidSize        *int32
	Kill            bool
	BossPercentage  pgtype.Numeric
	FightPercentage pgtype.Numeric
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
}

func (q *Queries) InsertEventReportFight(ctx context.Context, arg InsertEventReportFightParams) error {
	_, err := q.db.Exec(ctx, insertEventReportFight,
		arg.EventID,
		arg.FightID,
		arg.EncounterID,
		arg.Name,
		arg.Difficulty,
		arg.RaidSize,
		arg.Kill,
		arg.BossPercentage,
		arg.FightPercentage,
		arg.StartsAt,
		arg.EndsAt,
	)
	return err
}

const insertEventReportFightRaider = `-- name: InsertEventReportFightRaider :exec
INSERT INTO event_report_fight_raiders (
    event_id, fight_id, actor_id, actor_name, actor_server, class, character_id,
    damage, healing, deaths
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7,
    $8, $9, $10
)
ON CONFLICT (event_id, fight_id, actor_id) DO UPDATE SET
    actor_name = EXCLUDED.actor_name,
    actor_server = EXCLUDED.actor_server,
    class = EXCLUDED.class,
    character_id = EXCLUDED.character_id,
    damage = EXCLUDED.damage,
    healing = EXCLUDED.healing,
    deaths = EXCLUDED.deaths
`

type InsertEventReportFightRaiderParams struct {
	EventID     uuid.UUID
	FightID     int32
	ActorID     int32
	ActorName   string
	ActorServer string
	Class       *string
	CharacterID pgtype.UUID
	Damage      int64
	Healing     int64
	Deaths      int32
}

func (q *Queries) InsertEventReportFightRaider(ctx context.Context, arg InsertEventReportFightRaiderParams) error {
	_, err := q.db.Exec(ctx, insertEventReportFightRaider,
		arg.EventID,
		arg.FightID,
		arg.ActorID,
		arg.ActorName,
		arg.ActorServer,
		arg.Class,
		arg.CharacterID,
		arg.Damage,
		arg.Healing,
		arg.Deaths,
	)
	return err
}

const insertEventReportRaider = `-- name: InsertEventReportRaider :exec
INSERT INTO event_report_raiders (
    event_id, actor_id, actor_name, actor_server, class, character_id,
    damage, healing, deaths
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9
)
ON CONFLICT (event_id, actor_id) DO UPDATE SET
    actor_name = EXCLUDED.actor_name,
    actor_server = EXCLUDED.actor_server,
    class = EXCLUDED.class,
    -- Rematched on every fetch, so a raider who registers their alt on Thursday sees
    -- Wednesday's log light up without anybody touching it.
    character_id = EXCLUDED.character_id,
    damage = EXCLUDED.damage,
    healing = EXCLUDED.healing,
    deaths = EXCLUDED.deaths
`

type InsertEventReportRaiderParams struct {
	EventID     uuid.UUID
	ActorID     int32
	ActorName   string
	ActorServer string
	Class       *string
	CharacterID pgtype.UUID
	Damage      int64
	Healing     int64
	Deaths      int32
}

// The night's totals. Per-pull rows live in their own table, so a reader of this one sees
// one row per raider and cannot double-count.
func (q *Queries) InsertEventReportRaider(ctx context.Context, arg InsertEventReportRaiderParams) error {
	_, err := q.db.Exec(ctx, insertEventReportRaider,
		arg.EventID,
		arg.ActorID,
		arg.ActorName,
		arg.ActorServer,
		arg.Class,
		arg.CharacterID,
		arg.Damage,
		arg.Healing,
		arg.Deaths,
	)
	return err
}

const listEventReportFightRaiders = `-- name: ListEventReportFightRaiders :many
SELECT event_id, fight_id, actor_id, actor_name, actor_server, class, character_id, damage, healing, deaths FROM event_report_fight_raiders
WHERE event_id = $1
ORDER BY fight_id, damage DESC, actor_name
`

// Every pull's rows in one query, so a client selecting a pull costs no round trip.
func (q *Queries) ListEventReportFightRaiders(ctx context.Context, eventID uuid.UUID) ([]EventReportFightRaider, error) {
	rows, err := q.db.Query(ctx, listEventReportFightRaiders, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventReportFightRaider
	for rows.Next() {
		var i EventReportFightRaider
		if err := rows.Scan(
			&i.EventID,
			&i.FightID,
			&i.ActorID,
			&i.ActorName,
			&i.ActorServer,
			&i.Class,
			&i.CharacterID,
			&i.Damage,
			&i.Healing,
			&i.Deaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventReportFights = `-- name: ListEventReportFights :many
SELECT event_id, fight_id, encounter_id, name, difficulty, raid_size, kill, boss_percentage, fight_percentage, starts_at, ends_at FROM event_report_fights
WHERE event_id = $1
ORDER BY starts_at, fight_id
`

// In the order they happened, which is the order a raid night is read in.
func (q *Queries) ListEventReportFights(ctx context.Context, eventID uuid.UUID) ([]EventReportFight, error) {
	rows, err := q.db.Query(ctx, listEventReportFights, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventReportFight
	for rows.Next() {
		var i EventReportFight
		if err := rows.Scan(
			&i.EventID,
			&i.FightID,
			&i.EncounterID,
			&i.Name,
			&i.Difficulty,
			&i.RaidSize,
			&i.Kill,
			&i.BossPercentage,
			&i.FightPercentage,
			&i.StartsAt,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventReportRaiders = `-- name: ListEventReportRaiders :many
SELECT event_id, actor_id, actor_name, actor_server, class, character_id, damage, healing, deaths FROM event_report_raiders
WHERE event_id = $1
ORDER BY damage DESC, actor_name
`

// The night's totals, one row per raider.
//
// Damage first, because the damage board is what the page opens on. The read side
// reorders for the other two metrics rather than asking again.
func (q *Queries) ListEventReportRaiders(ctx context.Context, eventID uuid.UUID) ([]EventReportRaider, error) {
	rows, err := q.db.Query(ctx, listEventReportRaiders, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventReportRaider
	for rows.Next() {
		var i EventReportRaider
		if err := rows.Scan(
			&i.EventID,
			&i.ActorID,
			&i.ActorName,
			&i.ActorServer,
			&i.Class,
			&i.CharacterID,
			&i.Damage,
			&i.Healing,
			&i.Deaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpectedCharactersForEvent = `-- name: ListExpectedCharactersForEvent :many
SELECT character_id FROM signups
WHERE event_id = $1
  AND status IN ('CONFIRMED', 'LATE')
`

// Who said they were coming. CONFIRMED and LATE only: a tentative signup was never a
// promise, and listing a maybe as missing would put somebody on a no-show list for
// answering honestly.
func (q *Queries) ListExpectedCharactersForEvent(ctx context.Context, eventID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpectedCharactersForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var character_id uuid.UUID
		if err := rows.Scan(&character_id); err != nil {
			return nil, err
		}
		items = append(items, character_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReportFailed = `-- name: MarkReportFailed :exec
UPDATE event_reports SET
    status = $1,
    fetched_at = fetched_at,
    next_attempt_at = $2,
    attempts = attempts + 1,
    failure_reason = $3
WHERE event_id = $4
`

type MarkReportFailedParams struct {
	Status        ReportStatus
	NextAttemptAt pgtype.Timestamptz
	FailureReason *string
	EventID       uuid.UUID
}

// A failure leaves whatever numbers are already stored alone. A report that read fine
// yesterday and could not be reached today is still the best answer there is, and
// blanking it because one fetch failed would lose a night to an outage.
func (q *Queries) MarkReportFailed(ctx context.Context, arg MarkReportFailedParams) error {
	_, err := q.db.Exec(ctx, markReportFailed,
		arg.Status,
		arg.NextAttemptAt,
		arg.FailureReason,
		arg.EventID,
	)
	return err
}

const markReportFetched = `-- name: MarkReportFetched :exec
UPDATE event_reports SET
    status = 'READY',
    revision = $1,
    live = $2,
    title = $3,
    zone_name = $4,
    region = $5,
    report_starts_at = $6,
    report_ends_at = $7,
    fetched_at = now(),
    next_attempt_at = $8,
    attempts = 0,
    failure_reason = NULL
WHERE event_id = $9
`

type MarkReportFetchedParams struct {
	Revision       *int32
	Live           bool
	Title          *string
	ZoneName       *string
	Region         *string
	ReportStartsAt pgtype.Timestamptz
	ReportEndsAt   pgtype.Timestamptz
	NextAttemptAt  pgtype.Timestamptz
	EventID        uuid.UUID
}

// A successful read. next_attempt_at NULL is the row saying it has settled and the
// worker may stop asking; a timestamp is a report still being written to.
func (q *Queries) MarkReportFetched(ctx context.Context, arg MarkReportFetchedParams) error {
	_, err := q.db.Exec(ctx, markReportFetched,
		arg.Revision,
		arg.Live,
		arg.Title,
		arg.ZoneName,
		arg.Region,
		arg.ReportStartsAt,
		arg.ReportEndsAt,
		arg.NextAttemptAt,
		arg.EventID,
	)
	return err
}

const rescheduleReport = `-- name: RescheduleReport :exec
UPDATE event_reports SET next_attempt_at = $1
WHERE event_id = $2
`

type RescheduleReportParams struct {
	NextAttemptAt pgtype.Timestamptz
	EventID       uuid.UUID
}

// Puts a claimed row back without counting an attempt against it. For the cases where
// nothing was learned about the report itself: the point budget was spent, or the
// credentials were rejected.
func (q *Queries) RescheduleReport(ctx context.Context, arg RescheduleReportParams) error {
	_, err := q.db.Exec(ctx, rescheduleReport, arg.NextAttemptAt, arg.EventID)
	return err
}

const setGuildWarcraftLogsCredentials = `-- name: SetGuildWarcraftLogsCredentials :exec
INSERT INTO guild_settings (discord_guild_id, warcraft_logs_client_id, warcraft_logs_key_sealed, warcraft_logs_key_set_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (discord_guild_id) DO UPDATE
SET warcraft_logs_client_id = excluded.warcraft_logs_client_id,
    warcraft_logs_key_sealed = excluded.warcraft_logs_key_sealed,
    warcraft_logs_key_set_at = now(),
    updated_at = now()
`

type SetGuildWarcraftLogsCredentialsParams struct {
	DiscordGuildID int64
	ClientID       *string
	KeySealed      []byte
}

// Upsert, because a guild that has never been configured has no settings row.
func (q *Queries) SetGuildWarcraftLogsCredentials(ctx context.Context, arg SetGuildWarcraftLogsCredentialsParams) error {
	_, err := q.db.Exec(ctx, setGuildWarcraftLogsCredentials, arg.DiscordGuildID, arg.ClientID, arg.KeySealed)
	return err
}

const upsertEventReport = `-- name: UpsertEventReport :one
INSERT INTO event_reports (event_id, host, code, status, next_attempt_at)
VALUES ($1, $2, $3, 'PENDING', now())
ON CONFLICT (event_id) DO UPDATE SET
    host = EXCLUDED.host,
    code = EXCLUDED.code,
    status = CASE
        WHEN event_reports.code = EXCLUDED.code THEN event_reports.status
        ELSE 'PENDING'
    END,
    revision = CASE WHEN event_reports.code = EXCLUDED.code THEN event_reports.revision END,
    next_attempt_at = now(),
    attempts = 0,
    failure_reason = NULL
RETURNING event_id, host, code, status, revision, live, title, zone_name, region, report_starts_at, report_ends_at, fetched_at, next_attempt_at, attempts, failure_reason
`

type UpsertEventReportParams struct {
	EventID uuid.UUID
	Host    string
	Code    string
}

// Called in the same transaction as the event's URL write. A URL stored with no queue
// row behind it is a report nobody will ever fetch, so the two land together.
//
// A changed report is a new report: the code moving means the old fights and raiders
// describe a different night, and the cascade takes them with the row's reset. Due
// immediately, because a raid lead who just pasted a link is waiting for it.
func (q *Queries) UpsertEventReport(ctx context.Context, arg UpsertEventReportParams) (EventReport, error) {
	row := q.db.QueryRow(ctx, upsertEventReport, arg.EventID, arg.Host, arg.Code)
	var i EventReport
	err := row.Scan(
		&i.EventID,
		&i.Host,
		&i.Code,
		&i.Status,
		&i.Revision,
		&i.Live,
		&i.Title,
		&i.ZoneName,
		&i.Region,
		&i.ReportStartsAt,
		&i.ReportEndsAt,
		&i.FetchedAt,
		&i.NextAttemptAt,
		&i.Attempts,
		&i.FailureReason,
	)
	return i, err
}
