// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roster.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearMainForCharacterOwner = `-- name: ClearMainForCharacterOwner :exec
UPDATE characters SET is_main = false
WHERE is_main
  AND user_id = (
      SELECT c.user_id FROM characters c
      JOIN users u ON u.id = c.user_id
      WHERE c.id = $1 AND u.discord_guild_id = $2
  )
`

type ClearMainForCharacterOwnerParams struct {
	ID             uuid.UUID
	DiscordGuildID int64
}

// Demotes whichever character currently holds main for the owner of $1. Its own
// statement because characters_one_main_per_user is a partial unique index, and
// Postgres cannot defer one: a single UPDATE that demotes and promotes in one pass
// violates it whenever the scan reaches the promoted row first, which makes the bug
// depend on heap order rather than on the data. Run this and SetCharacterMain inside
// one transaction. A character in another guild matches nothing, so the subquery
// returning NULL is the guild scoping.
func (q *Queries) ClearMainForCharacterOwner(ctx context.Context, arg ClearMainForCharacterOwnerParams) error {
	_, err := q.db.Exec(ctx, clearMainForCharacterOwner, arg.ID, arg.DiscordGuildID)
	return err
}

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (id, user_id, name, realm, region, is_main)
SELECT
    $1, $2, $3, $4, $5,
    $6::boolean
        AND NOT EXISTS (
            SELECT 1 FROM characters x WHERE x.user_id = $2 AND x.is_main
        )
RETURNING id, user_id, name, realm, class, spec, ilvl, mplus_score, last_synced, is_main, region, sync_attempted_at, enchants_missing, enchants_expected, tier_pieces, raid_slug, raid_bosses, raid_normal_killed, raid_heroic_killed, raid_mythic_killed, archived_at, not_found_since
`

type CreateCharacterParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Name   string
	Realm  string
	Region string
	IsMain bool
}

// is_main is decided here rather than taken from the caller. "My main" is a fact about
// the whole roster, not about the row being written, and a client that sends true on
// every registration would have each new alt steal the flag from the character that
// holds it. The caller's value is a request, granted only while the raider has no main
// yet; moving it afterwards is SetCharacterMain, which demotes the old one first.
func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, createCharacter,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Realm,
		arg.Region,
		arg.IsMain,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Realm,
		&i.Class,
		&i.Spec,
		&i.Ilvl,
		&i.MplusScore,
		&i.LastSynced,
		&i.IsMain,
		&i.Region,
		&i.SyncAttemptedAt,
		&i.EnchantsMissing,
		&i.EnchantsExpected,
		&i.TierPieces,
		&i.RaidSlug,
		&i.RaidBosses,
		&i.RaidNormalKilled,
		&i.RaidHeroicKilled,
		&i.RaidMythicKilled,
		&i.ArchivedAt,
		&i.NotFoundSince,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :execrows
DELETE FROM characters c
USING users u
WHERE c.user_id = u.id AND c.id = $1 AND u.discord_guild_id = $2
`

type DeleteCharacterParams struct {
	ID             uuid.UUID
	DiscordGuildID int64
}

// Guild-scoped so a character id alone cannot delete another guild's row. The
// affected-row count is what tells the caller "no such character here" apart from
// "deleted", which a plain :exec cannot.
func (q *Queries) DeleteCharacter(ctx context.Context, arg DeleteCharacterParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCharacter, arg.ID, arg.DiscordGuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCharacterRoles = `-- name: DeleteCharacterRoles :exec
DELETE FROM character_roles
WHERE character_id = $1
`

func (q *Queries) DeleteCharacterRoles(ctx context.Context, characterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCharacterRoles, characterID)
	return err
}

const getCharacterInGuild = `-- name: GetCharacterInGuild :one
SELECT c.id, c.user_id, c.name, c.realm, c.class, c.spec, c.ilvl, c.mplus_score, c.last_synced, c.is_main, c.region, c.sync_attempted_at, c.enchants_missing, c.enchants_expected, c.tier_pieces, c.raid_slug, c.raid_bosses, c.raid_normal_killed, c.raid_heroic_killed, c.raid_mythic_killed, c.archived_at, c.not_found_since FROM characters c
JOIN users u ON u.id = c.user_id
WHERE c.id = $1 AND u.discord_guild_id = $2
`

type GetCharacterInGuildParams struct {
	ID             uuid.UUID
	DiscordGuildID int64
}

func (q *Queries) GetCharacterInGuild(ctx context.Context, arg GetCharacterInGuildParams) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterInGuild, arg.ID, arg.DiscordGuildID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Realm,
		&i.Class,
		&i.Spec,
		&i.Ilvl,
		&i.MplusScore,
		&i.LastSynced,
		&i.IsMain,
		&i.Region,
		&i.SyncAttemptedAt,
		&i.EnchantsMissing,
		&i.EnchantsExpected,
		&i.TierPieces,
		&i.RaidSlug,
		&i.RaidBosses,
		&i.RaidNormalKilled,
		&i.RaidHeroicKilled,
		&i.RaidMythicKilled,
		&i.ArchivedAt,
		&i.NotFoundSince,
	)
	return i, err
}

const getCharacterOwner = `-- name: GetCharacterOwner :one
SELECT u.discord_id FROM characters c
JOIN users u ON u.id = c.user_id
WHERE c.id = $1 AND u.discord_guild_id = $2
`

type GetCharacterOwnerParams struct {
	ID             uuid.UUID
	DiscordGuildID int64
}

// A signup write is "self, or raid lead": self means the caller's discord id owns
// the character, which the signup and late-request handlers cannot decide without
// this.
func (q *Queries) GetCharacterOwner(ctx context.Context, arg GetCharacterOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, getCharacterOwner, arg.ID, arg.DiscordGuildID)
	var discord_id int64
	err := row.Scan(&discord_id)
	return discord_id, err
}

const getUserByDiscord = `-- name: GetUserByDiscord :one
SELECT id, discord_id, discord_guild_id, created_at FROM users
WHERE discord_id = $1 AND discord_guild_id = $2
`

type GetUserByDiscordParams struct {
	DiscordID      int64
	DiscordGuildID int64
}

func (q *Queries) GetUserByDiscord(ctx context.Context, arg GetUserByDiscordParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDiscord, arg.DiscordID, arg.DiscordGuildID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordGuildID,
		&i.CreatedAt,
	)
	return i, err
}

const listCharacterRoles = `-- name: ListCharacterRoles :many
SELECT character_id, role, priority FROM character_roles
WHERE character_id = $1
ORDER BY priority, role
`

// Nothing stops two roles sharing a priority; role keeps the menu order stable.
func (q *Queries) ListCharacterRoles(ctx context.Context, characterID uuid.UUID) ([]CharacterRole, error) {
	rows, err := q.db.Query(ctx, listCharacterRoles, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CharacterRole
	for rows.Next() {
		var i CharacterRole
		if err := rows.Scan(&i.CharacterID, &i.Role, &i.Priority); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersByDiscord = `-- name: ListCharactersByDiscord :many
SELECT c.id, c.user_id, c.name, c.realm, c.class, c.spec, c.ilvl, c.mplus_score, c.last_synced, c.is_main, c.region, c.sync_attempted_at, c.enchants_missing, c.enchants_expected, c.tier_pieces, c.raid_slug, c.raid_bosses, c.raid_normal_killed, c.raid_heroic_killed, c.raid_mythic_killed, c.archived_at, c.not_found_since FROM characters c
JOIN users u ON u.id = c.user_id
WHERE u.discord_id = $1 AND u.discord_guild_id = $2
ORDER BY c.name
`

type ListCharactersByDiscordParams struct {
	DiscordID      int64
	DiscordGuildID int64
}

func (q *Queries) ListCharactersByDiscord(ctx context.Context, arg ListCharactersByDiscordParams) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharactersByDiscord, arg.DiscordID, arg.DiscordGuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Realm,
			&i.Class,
			&i.Spec,
			&i.Ilvl,
			&i.MplusScore,
			&i.LastSynced,
			&i.IsMain,
			&i.Region,
			&i.SyncAttemptedAt,
			&i.EnchantsMissing,
			&i.EnchantsExpected,
			&i.TierPieces,
			&i.RaidSlug,
			&i.RaidBosses,
			&i.RaidNormalKilled,
			&i.RaidHeroicKilled,
			&i.RaidMythicKilled,
			&i.ArchivedAt,
			&i.NotFoundSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersByUser = `-- name: ListCharactersByUser :many
SELECT id, user_id, name, realm, class, spec, ilvl, mplus_score, last_synced, is_main, region, sync_attempted_at, enchants_missing, enchants_expected, tier_pieces, raid_slug, raid_bosses, raid_normal_killed, raid_heroic_killed, raid_mythic_killed, archived_at, not_found_since FROM characters
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListCharactersByUser(ctx context.Context, userID uuid.UUID) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharactersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Realm,
			&i.Class,
			&i.Spec,
			&i.Ilvl,
			&i.MplusScore,
			&i.LastSynced,
			&i.IsMain,
			&i.Region,
			&i.SyncAttemptedAt,
			&i.EnchantsMissing,
			&i.EnchantsExpected,
			&i.TierPieces,
			&i.RaidSlug,
			&i.RaidBosses,
			&i.RaidNormalKilled,
			&i.RaidHeroicKilled,
			&i.RaidMythicKilled,
			&i.ArchivedAt,
			&i.NotFoundSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersDueForSync = `-- name: ListCharactersDueForSync :many
SELECT id, user_id, name, realm, class, spec, ilvl, mplus_score, last_synced, is_main, region, sync_attempted_at, enchants_missing, enchants_expected, tier_pieces, raid_slug, raid_bosses, raid_normal_killed, raid_heroic_killed, raid_mythic_killed, archived_at, not_found_since FROM characters
WHERE (last_synced IS NULL OR last_synced < $1)
  AND (sync_attempted_at IS NULL OR sync_attempted_at < $1)
ORDER BY sync_attempted_at ASC NULLS FIRST
LIMIT $2
`

type ListCharactersDueForSyncParams struct {
	StaleBefore pgtype.Timestamptz
	RowLimit    int32
}

// Oldest-attempted first so a backlog drains fairly instead of starving whoever is
// always at the bottom of an ID-ordered scan. Ordering by attempt rather than by
// last_synced keeps a character whose fetch keeps failing from holding the head of
// every batch.
func (q *Queries) ListCharactersDueForSync(ctx context.Context, arg ListCharactersDueForSyncParams) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharactersDueForSync, arg.StaleBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Realm,
			&i.Class,
			&i.Spec,
			&i.Ilvl,
			&i.MplusScore,
			&i.LastSynced,
			&i.IsMain,
			&i.Region,
			&i.SyncAttemptedAt,
			&i.EnchantsMissing,
			&i.EnchantsExpected,
			&i.TierPieces,
			&i.RaidSlug,
			&i.RaidBosses,
			&i.RaidNormalKilled,
			&i.RaidHeroicKilled,
			&i.RaidMythicKilled,
			&i.ArchivedAt,
			&i.NotFoundSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersInGuild = `-- name: ListCharactersInGuild :many
SELECT c.id, c.user_id, c.name, c.realm, c.class, c.spec, c.ilvl, c.mplus_score, c.last_synced, c.is_main, c.region, c.sync_attempted_at, c.enchants_missing, c.enchants_expected, c.tier_pieces, c.raid_slug, c.raid_bosses, c.raid_normal_killed, c.raid_heroic_killed, c.raid_mythic_killed, c.archived_at, c.not_found_since FROM characters c
JOIN users u ON u.id = c.user_id
WHERE u.discord_guild_id = $1
  AND ($2::boolean OR c.archived_at IS NULL)
ORDER BY c.name
`

type ListCharactersInGuildParams struct {
	DiscordGuildID  int64
	IncludeArchived bool
}

// The archived are off the roster by default and readable on request, never gone: the
// signup, comp and analysis reads join characters directly and must keep seeing them,
// or a leaver takes their own raid history with them.
func (q *Queries) ListCharactersInGuild(ctx context.Context, arg ListCharactersInGuildParams) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharactersInGuild, arg.DiscordGuildID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Realm,
			&i.Class,
			&i.Spec,
			&i.Ilvl,
			&i.MplusScore,
			&i.LastSynced,
			&i.IsMain,
			&i.Region,
			&i.SyncAttemptedAt,
			&i.EnchantsMissing,
			&i.EnchantsExpected,
			&i.TierPieces,
			&i.RaidSlug,
			&i.RaidBosses,
			&i.RaidNormalKilled,
			&i.RaidHeroicKilled,
			&i.RaidMythicKilled,
			&i.ArchivedAt,
			&i.NotFoundSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildsForDiscordUser = `-- name: ListGuildsForDiscordUser :many
SELECT DISTINCT u.discord_guild_id
FROM users u
JOIN characters c ON c.user_id = u.id
WHERE u.discord_id = $1
ORDER BY u.discord_guild_id
`

// The guilds Raider Mate actually knows this person in, which is not the same as the
// guilds they are in on Discord. Joined through characters on purpose: a users row with
// nothing attached would send a client to a guild with an empty roster.
func (q *Queries) ListGuildsForDiscordUser(ctx context.Context, discordID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listGuildsForDiscordUser, discordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var discord_guild_id int64
		if err := rows.Scan(&discord_guild_id); err != nil {
			return nil, err
		}
		items = append(items, discord_guild_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCharacterNotFound = `-- name: MarkCharacterNotFound :exec
UPDATE characters SET
    sync_attempted_at = now(),
    not_found_since = COALESCE(not_found_since, now())
WHERE id = $1
`

// Raider.IO answered 404. The queue moves on and the stored numbers stay put, because
// they are the last true thing known about this character, but the row now says since
// when nobody has been able to confirm them. COALESCE keeps the first sighting: the
// date a raid lead reads is when the character went missing, not when it was last
// looked for.
func (q *Queries) MarkCharacterNotFound(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCharacterNotFound, id)
	return err
}

const markCharacterSyncAttempted = `-- name: MarkCharacterSyncAttempted :exec
UPDATE characters SET sync_attempted_at = now()
WHERE id = $1
`

// A failed fetch. last_synced stays put because the cached data did not get any
// fresher; only the queue position moves.
func (q *Queries) MarkCharacterSyncAttempted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCharacterSyncAttempted, id)
	return err
}

const setCharacterArchived = `-- name: SetCharacterArchived :execrows
UPDATE characters c SET archived_at = CASE
    WHEN NOT $1::boolean THEN NULL
    ELSE COALESCE(c.archived_at, now())
END
FROM users u
WHERE c.user_id = u.id AND c.id = $2 AND u.discord_guild_id = $3
`

type SetCharacterArchivedParams struct {
	Archived       bool
	ID             uuid.UUID
	DiscordGuildID int64
}

// Guild-scoped, and idempotent on the way in: re-archiving keeps the date the raider
// actually left rather than stamping today over it. Un-archiving clears it outright.
func (q *Queries) SetCharacterArchived(ctx context.Context, arg SetCharacterArchivedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCharacterArchived, arg.Archived, arg.ID, arg.DiscordGuildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCharacterMain = `-- name: SetCharacterMain :execrows
UPDATE characters c SET is_main = $3
FROM users u
WHERE c.user_id = u.id AND c.id = $1 AND u.discord_guild_id = $2
`

type SetCharacterMainParams struct {
	ID             uuid.UUID
	DiscordGuildID int64
	IsMain         bool
}

// Same guild scoping and the same reason for :execrows. Only is_main is settable:
// name, realm and region are the Raider.IO identity the sync job keys on, so
// changing them is a delete and a re-register, not an edit.
func (q *Queries) SetCharacterMain(ctx context.Context, arg SetCharacterMainParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCharacterMain, arg.ID, arg.DiscordGuildID, arg.IsMain)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCharacterRole = `-- name: SetCharacterRole :exec
INSERT INTO character_roles (character_id, role, priority)
VALUES ($1, $2, $3)
ON CONFLICT (character_id, role) DO UPDATE SET priority = excluded.priority
`

type SetCharacterRoleParams struct {
	CharacterID uuid.UUID
	Role        RoleEnum
	Priority    int16
}

func (q *Queries) SetCharacterRole(ctx context.Context, arg SetCharacterRoleParams) error {
	_, err := q.db.Exec(ctx, setCharacterRole, arg.CharacterID, arg.Role, arg.Priority)
	return err
}

const touchCharacterSynced = `-- name: TouchCharacterSynced :exec
UPDATE characters SET last_synced = now(), sync_attempted_at = now(), not_found_since = NULL
WHERE id = $1
`

// A fetch that found the character and changed nothing. Clears not_found_since, so a
// raider who came back from a rename stops reading as missing.
func (q *Queries) TouchCharacterSynced(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchCharacterSynced, id)
	return err
}

const updateCharacterFromSync = `-- name: UpdateCharacterFromSync :exec
UPDATE characters SET
    class = COALESCE($4, class),
    spec = COALESCE($5, spec),
    ilvl = $2,
    mplus_score = $3,
    enchants_missing = $6,
    enchants_expected = $7,
    tier_pieces = $8,
    raid_slug = $9,
    raid_bosses = $10,
    raid_normal_killed = $11,
    raid_heroic_killed = $12,
    raid_mythic_killed = $13,
    last_synced = now(),
    sync_attempted_at = now(),
    -- The fetch found them, so whatever they were missing from, they are back.
    not_found_since = NULL
WHERE id = $1
`

type UpdateCharacterFromSyncParams struct {
	ID               uuid.UUID
	Ilvl             pgtype.Numeric
	MplusScore       pgtype.Numeric
	Class            *string
	Spec             *string
	EnchantsMissing  *int16
	EnchantsExpected *int16
	TierPieces       *int16
	RaidSlug         *string
	RaidBosses       *int16
	RaidNormalKilled *int16
	RaidHeroicKilled *int16
	RaidMythicKilled *int16
}

// COALESCE so a response missing class or spec leaves the stored value alone
// instead of blanking it.
//
// The gear-derived columns below are written straight, NULL included, unlike class and
// spec. A raider who unequips their tier really does have no tier, and COALESCEing that
// away would leave last season's count on the row forever.
func (q *Queries) UpdateCharacterFromSync(ctx context.Context, arg UpdateCharacterFromSyncParams) error {
	_, err := q.db.Exec(ctx, updateCharacterFromSync,
		arg.ID,
		arg.Ilvl,
		arg.MplusScore,
		arg.Class,
		arg.Spec,
		arg.EnchantsMissing,
		arg.EnchantsExpected,
		arg.TierPieces,
		arg.RaidSlug,
		arg.RaidBosses,
		arg.RaidNormalKilled,
		arg.RaidHeroicKilled,
		arg.RaidMythicKilled,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, discord_id, discord_guild_id)
VALUES ($1, $2, $3)
ON CONFLICT (discord_id, discord_guild_id) DO UPDATE SET discord_id = excluded.discord_id
RETURNING id, discord_id, discord_guild_id, created_at
`

type UpsertUserParams struct {
	ID             uuid.UUID
	DiscordID      int64
	DiscordGuildID int64
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.ID, arg.DiscordID, arg.DiscordGuildID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordGuildID,
		&i.CreatedAt,
	)
	return i, err
}
