// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signup.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCompSlotsForEvent = `-- name: CountCompSlotsForEvent :one
SELECT count(*) FROM comp_slots WHERE event_id = $1
`

func (q *Queries) CountCompSlotsForEvent(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompSlotsForEvent, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSignupsByStatusForEvents = `-- name: CountSignupsByStatusForEvents :many
SELECT event_id, status, count(*) AS total
FROM signups
WHERE event_id = ANY($1::uuid[])
GROUP BY event_id, status
`

type CountSignupsByStatusForEventsRow struct {
	EventID uuid.UUID
	Status  SignupStatus
	Total   int64
}

// The tally behind an event's signup_counts, for a whole guild's list in one query.
// Grouped in SQL rather than by reading every signup row and counting in Go: a month
// of raid nights is a request per event otherwise, each one dragging back full signup
// rows in order to learn how many there are.
//
// Only statuses actually present come back. Seeding the absent ones at zero is the
// caller's job, because the enum lives in Go and a client rendering "0 absent" needs
// the key present.
func (q *Queries) CountSignupsByStatusForEvents(ctx context.Context, eventIds []uuid.UUID) ([]CountSignupsByStatusForEventsRow, error) {
	rows, err := q.db.Query(ctx, countSignupsByStatusForEvents, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountSignupsByStatusForEventsRow
	for rows.Next() {
		var i CountSignupsByStatusForEventsRow
		if err := rows.Scan(&i.EventID, &i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, discord_guild_id, type, title, starts_at, signup_deadline, comp_template, message_id, channel_id, difficulty, reminder_lead_minutes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, discord_guild_id, type, title, starts_at, signup_deadline, comp_template, message_id, channel_id, difficulty, reminder_lead_minutes, warcraftlogs_url
`

type CreateEventParams struct {
	ID                  uuid.UUID
	DiscordGuildID      int64
	Type                EventType
	Title               string
	StartsAt            pgtype.Timestamptz
	SignupDeadline      pgtype.Timestamptz
	CompTemplate        []byte
	MessageID           *int64
	ChannelID           *int64
	Difficulty          *RaidDifficulty
	ReminderLeadMinutes *int32
}

// difficulty is NULL for MYTHIC_PLUS events, which have no difficulty of their own.
// For a raid it decides the comp size rule, so the assigner cannot tell a Mythic
// raid from a flex one without it.
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.DiscordGuildID,
		arg.Type,
		arg.Title,
		arg.StartsAt,
		arg.SignupDeadline,
		arg.CompTemplate,
		arg.MessageID,
		arg.ChannelID,
		arg.Difficulty,
		arg.ReminderLeadMinutes,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.DiscordGuildID,
		&i.Type,
		&i.Title,
		&i.StartsAt,
		&i.SignupDeadline,
		&i.CompTemplate,
		&i.MessageID,
		&i.ChannelID,
		&i.Difficulty,
		&i.ReminderLeadMinutes,
		&i.WarcraftlogsUrl,
	)
	return i, err
}

const decideLateRequest = `-- name: DecideLateRequest :exec
UPDATE late_signup_requests SET state = $2, decided_at = now()
WHERE id = $1
`

type DecideLateRequestParams struct {
	ID    uuid.UUID
	State RequestState
}

func (q *Queries) DecideLateRequest(ctx context.Context, arg DecideLateRequestParams) error {
	_, err := q.db.Exec(ctx, decideLateRequest, arg.ID, arg.State)
	return err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const deleteSignup = `-- name: DeleteSignup :exec
DELETE FROM signups
WHERE event_id = $1 AND character_id = $2
`

type DeleteSignupParams struct {
	EventID     uuid.UUID
	CharacterID uuid.UUID
}

func (q *Queries) DeleteSignup(ctx context.Context, arg DeleteSignupParams) error {
	_, err := q.db.Exec(ctx, deleteSignup, arg.EventID, arg.CharacterID)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, discord_guild_id, type, title, starts_at, signup_deadline, comp_template, message_id, channel_id, difficulty, reminder_lead_minutes, warcraftlogs_url FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.DiscordGuildID,
		&i.Type,
		&i.Title,
		&i.StartsAt,
		&i.SignupDeadline,
		&i.CompTemplate,
		&i.MessageID,
		&i.ChannelID,
		&i.Difficulty,
		&i.ReminderLeadMinutes,
		&i.WarcraftlogsUrl,
	)
	return i, err
}

const getLateRequest = `-- name: GetLateRequest :one
SELECT id, event_id, character_id, status, note, state, created_at, decided_at, late_until FROM late_signup_requests
WHERE id = $1
`

// Approving needs the event/character/status the request was filed with; the
// decide endpoints only carry the request id.
func (q *Queries) GetLateRequest(ctx context.Context, id uuid.UUID) (LateSignupRequest, error) {
	row := q.db.QueryRow(ctx, getLateRequest, id)
	var i LateSignupRequest
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.CharacterID,
		&i.Status,
		&i.Note,
		&i.State,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.LateUntil,
	)
	return i, err
}

const listAttendingForEvent = `-- name: ListAttendingForEvent :many
SELECT DISTINCT ON (u.discord_id) u.discord_id, s.assigned_role
FROM signups s
JOIN characters c ON c.id = s.character_id
JOIN users u ON u.id = c.user_id
WHERE s.event_id = $1
  AND s.status IN ('CONFIRMED', 'LATE', 'TENTATIVE')
ORDER BY u.discord_id, (s.assigned_role IS NULL)
`

type ListAttendingForEventRow struct {
	DiscordID    int64
	AssignedRole *RoleEnum
}

// Everyone who said they are turning up, seated or not. The pre-event reminder does not
// read the comp: a raider left out of a locked twenty still wants to know the raid is
// about to pull, and an unlocked event has no assignments at all.
//
// DISTINCT ON collapses a person's alts to one row, preferring the alt that holds a
// seat so the DM can still name a role. Without it, four signed-up alts is four pings
// of the same person.
func (q *Queries) ListAttendingForEvent(ctx context.Context, eventID uuid.UUID) ([]ListAttendingForEventRow, error) {
	rows, err := q.db.Query(ctx, listAttendingForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttendingForEventRow
	for rows.Next() {
		var i ListAttendingForEventRow
		if err := rows.Scan(&i.DiscordID, &i.AssignedRole); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLateRequests = `-- name: ListLateRequests :many
SELECT id, event_id, character_id, status, note, state, created_at, decided_at, late_until FROM late_signup_requests
WHERE event_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLateRequests(ctx context.Context, eventID uuid.UUID) ([]LateSignupRequest, error) {
	rows, err := q.db.Query(ctx, listLateRequests, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LateSignupRequest
	for rows.Next() {
		var i LateSignupRequest
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.CharacterID,
			&i.Status,
			&i.Note,
			&i.State,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.LateUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPastEvents = `-- name: ListPastEvents :many
SELECT id, discord_guild_id, type, title, starts_at, signup_deadline, comp_template, message_id, channel_id, difficulty, reminder_lead_minutes, warcraftlogs_url FROM events
WHERE discord_guild_id = $1 AND starts_at < now()
ORDER BY starts_at DESC
`

// The complement of ListUpcomingEvents, so every event is in exactly one of the two.
// Newest first: a raid lead attaching a log is looking for last night, not for the
// guild's first ever raid.
func (q *Queries) ListPastEvents(ctx context.Context, discordGuildID int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, listPastEvents, discordGuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.DiscordGuildID,
			&i.Type,
			&i.Title,
			&i.StartsAt,
			&i.SignupDeadline,
			&i.CompTemplate,
			&i.MessageID,
			&i.ChannelID,
			&i.Difficulty,
			&i.ReminderLeadMinutes,
			&i.WarcraftlogsUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignupsForEvent = `-- name: ListSignupsForEvent :many
SELECT id, event_id, character_id, status, assigned_role, late_until, note, created_at FROM signups
WHERE event_id = $1
ORDER BY created_at ASC, id ASC
`

// created_at is transaction start time, so it ties for signups written together.
func (q *Queries) ListSignupsForEvent(ctx context.Context, eventID uuid.UUID) ([]Signup, error) {
	rows, err := q.db.Query(ctx, listSignupsForEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Signup
	for rows.Next() {
		var i Signup
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.CharacterID,
			&i.Status,
			&i.AssignedRole,
			&i.LateUntil,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUndecidedForEvent = `-- name: ListUndecidedForEvent :many
SELECT DISTINCT u.discord_id
FROM users u
JOIN events e ON e.discord_guild_id = u.discord_guild_id
WHERE e.id = $1
  AND EXISTS (
      SELECT 1 FROM characters c
      WHERE c.user_id = u.id
  )
  AND NOT EXISTS (
      SELECT 1 FROM signups s
      JOIN characters c2 ON c2.id = s.character_id
      WHERE s.event_id = e.id AND c2.user_id = u.id
  )
ORDER BY u.discord_id
`

// Grouped by discord_id, not by character: a raider with four alts and no signup is
// one person who has not answered, and four DMs would be a bug.
//
// NOT EXISTS over the whole user, not a LEFT JOIN per character. A join emits one row
// per *unsigned character*, so a raider who answered on their main but owns three
// untouched alts still matched and got nagged about an event they had already
// answered. Answering on any one character answers for the person.
func (q *Queries) ListUndecidedForEvent(ctx context.Context, id uuid.UUID) ([]int64, error) {
	rows, err := q.db.Query(ctx, listUndecidedForEvent, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var discord_id int64
		if err := rows.Scan(&discord_id); err != nil {
			return nil, err
		}
		items = append(items, discord_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEvents = `-- name: ListUpcomingEvents :many
SELECT id, discord_guild_id, type, title, starts_at, signup_deadline, comp_template, message_id, channel_id, difficulty, reminder_lead_minutes, warcraftlogs_url FROM events
WHERE discord_guild_id = $1 AND starts_at >= now()
ORDER BY starts_at ASC
`

func (q *Queries) ListUpcomingEvents(ctx context.Context, discordGuildID int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, listUpcomingEvents, discordGuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.DiscordGuildID,
			&i.Type,
			&i.Title,
			&i.StartsAt,
			&i.SignupDeadline,
			&i.CompTemplate,
			&i.MessageID,
			&i.ChannelID,
			&i.Difficulty,
			&i.ReminderLeadMinutes,
			&i.WarcraftlogsUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEventDifficulty = `-- name: SetEventDifficulty :exec
UPDATE events SET difficulty = $2
WHERE id = $1
`

type SetEventDifficultyParams struct {
	ID         uuid.UUID
	Difficulty *RaidDifficulty
}

func (q *Queries) SetEventDifficulty(ctx context.Context, arg SetEventDifficultyParams) error {
	_, err := q.db.Exec(ctx, setEventDifficulty, arg.ID, arg.Difficulty)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    title = COALESCE($1, title),
    starts_at = COALESCE($2, starts_at),
    signup_deadline = COALESCE($3, signup_deadline),
    comp_template = COALESCE($4, comp_template),
    difficulty = COALESCE($5, difficulty),
    message_id = COALESCE($6, message_id),
    channel_id = COALESCE($7, channel_id),
    reminder_lead_minutes = COALESCE($8, reminder_lead_minutes),
    -- The one field a PATCH can also clear. NULL keeps the stored value like every
    -- other column here, so an empty string is what "take the log off this event"
    -- looks like on the wire. An empty string is not a URL, so nothing is lost by
    -- spending it as the sentinel.
    warcraftlogs_url = CASE
        WHEN $9::text = '' THEN NULL
        ELSE COALESCE($9, warcraftlogs_url)
    END
WHERE id = $10
RETURNING id, discord_guild_id, type, title, starts_at, signup_deadline, comp_template, message_id, channel_id, difficulty, reminder_lead_minutes, warcraftlogs_url
`

type UpdateEventParams struct {
	Title               *string
	StartsAt            pgtype.Timestamptz
	SignupDeadline      pgtype.Timestamptz
	CompTemplate        []byte
	Difficulty          *RaidDifficulty
	MessageID           *int64
	ChannelID           *int64
	ReminderLeadMinutes *int32
	WarcraftlogsUrl     *string
	ID                  uuid.UUID
}

// Partial update: a field left NULL keeps its stored value, same COALESCE pattern as
// UpdateCharacterFromSync. Covers message_id/channel_id (learned only after the bot
// posts) and the schedule fields a PATCH reschedules jobs from.
func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.Title,
		arg.StartsAt,
		arg.SignupDeadline,
		arg.CompTemplate,
		arg.Difficulty,
		arg.MessageID,
		arg.ChannelID,
		arg.ReminderLeadMinutes,
		arg.WarcraftlogsUrl,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.DiscordGuildID,
		&i.Type,
		&i.Title,
		&i.StartsAt,
		&i.SignupDeadline,
		&i.CompTemplate,
		&i.MessageID,
		&i.ChannelID,
		&i.Difficulty,
		&i.ReminderLeadMinutes,
		&i.WarcraftlogsUrl,
	)
	return i, err
}

const upsertLateRequest = `-- name: UpsertLateRequest :one
INSERT INTO late_signup_requests (id, event_id, character_id, status, note, late_until)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (event_id, character_id) DO UPDATE SET
    status = excluded.status,
    note = excluded.note,
    late_until = excluded.late_until,
    state = 'PENDING',
    decided_at = NULL
RETURNING id, event_id, character_id, status, note, state, created_at, decided_at, late_until
`

type UpsertLateRequestParams struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	CharacterID uuid.UUID
	Status      SignupStatus
	Note        *string
	LateUntil   pgtype.Timestamptz
}

// A re-request resets state to PENDING and clears any prior decision, since the
// unique constraint makes this an upsert rather than a pile of rows.
func (q *Queries) UpsertLateRequest(ctx context.Context, arg UpsertLateRequestParams) (LateSignupRequest, error) {
	row := q.db.QueryRow(ctx, upsertLateRequest,
		arg.ID,
		arg.EventID,
		arg.CharacterID,
		arg.Status,
		arg.Note,
		arg.LateUntil,
	)
	var i LateSignupRequest
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.CharacterID,
		&i.Status,
		&i.Note,
		&i.State,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.LateUntil,
	)
	return i, err
}

const upsertSignup = `-- name: UpsertSignup :one
INSERT INTO signups (id, event_id, character_id, status, note, late_until)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (event_id, character_id) DO UPDATE SET
    status = excluded.status,
    note = excluded.note,
    late_until = excluded.late_until,
    assigned_role = CASE
        WHEN signups.status IS DISTINCT FROM excluded.status THEN NULL
        ELSE signups.assigned_role
    END
RETURNING id, event_id, character_id, status, assigned_role, late_until, note, created_at
`

type UpsertSignupParams struct {
	ID          uuid.UUID
	EventID     uuid.UUID
	CharacterID uuid.UUID
	Status      SignupStatus
	Note        *string
	LateUntil   pgtype.Timestamptz
}

// late_until is a plain write-through field, same as note: internal/signup owns the
// rule that it is only meaningful alongside status = LATE and nils it otherwise.
// A status change invalidates whatever the comp lock decided, so the assignment is
// dropped. Editing only the note leaves an existing assignment alone.
func (q *Queries) UpsertSignup(ctx context.Context, arg UpsertSignupParams) (Signup, error) {
	row := q.db.QueryRow(ctx, upsertSignup,
		arg.ID,
		arg.EventID,
		arg.CharacterID,
		arg.Status,
		arg.Note,
		arg.LateUntil,
	)
	var i Signup
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.CharacterID,
		&i.Status,
		&i.AssignedRole,
		&i.LateUntil,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
